"use client";

import * as React from "react";
import {
  FileText,
  Mail,
  ExternalLink,
  Copy,
  CheckCircle2,
  Building2,
  Globe,
  MapPin,
} from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ScoreBadge } from "@/components/jobs/ScoreBadge";
import { useJobs, useUpdateJobStatus } from "@/hooks/useJobs";
import { formatRelative } from "@/lib/utils";
import type { Job } from "@/lib/types";

const API_BASE =
  process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

const STATUS_LABEL: Record<string, string> = {
  prepared: "Prepared",
  applied: "Applied",
  interviewing: "Interviewing",
  offer: "Offer",
};

export default function ApplicationsPage() {
  const jobs = useJobs();
  const update = useUpdateJobStatus();

  const withDocs = React.useMemo(
    () =>
      (jobs.data ?? []).filter(
        (j) => !!j.cv_path || !!j.cover_letter_path,
      ),
    [jobs.data],
  );

  if (jobs.isLoading) {
    return <Skeleton className="h-96 w-full" />;
  }

  if (withDocs.length === 0) {
    return (
      <Card variant="glass">
        <CardContent className="grid place-items-center gap-3 py-16 text-center">
          <div className="grid h-12 w-12 place-items-center rounded-full bg-[hsl(var(--surface))]">
            <FileText className="h-5 w-5 text-muted-foreground" />
          </div>
          <div className="space-y-1">
            <h3 className="text-base font-semibold">No applications yet</h3>
            <p className="text-xs text-muted-foreground max-w-md">
              Generate a CV + cover for a job from /today to see it appear
              here, with quick links to open both PDFs in your browser.
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <Card variant="glass">
        <CardHeader>
          <CardTitle className="inline-flex items-center gap-2">
            <FileText className="h-4 w-4 text-[hsl(var(--accent-1))]" />
            Applications & generated documents
          </CardTitle>
          <p className="text-[11px] text-muted-foreground">
            All CVs and cover letters generated by Claude, ordered by latest.
            Click to open each PDF in a new tab.
          </p>
        </CardHeader>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
        {withDocs.map((job) => (
          <ApplicationCard
            key={job.id}
            job={job}
            onMarkApplied={async () => {
              try {
                await update.mutateAsync({ id: job.id, status: "applied" });
                toast.success("Marked as applied");
              } catch {
                toast.error("Failed to update status");
              }
            }}
          />
        ))}
      </div>
    </div>
  );
}

function ApplicationCard({
  job,
  onMarkApplied,
}: {
  job: Job;
  onMarkApplied: () => void;
}) {
  const cvUrl = `${API_BASE}/jobs/${job.id}/cv`;
  const coverUrl = `${API_BASE}/jobs/${job.id}/cover`;

  const copyPath = async (path: string, label: string) => {
    try {
      await navigator.clipboard.writeText(path);
      toast.success(`${label} path copied`, { duration: 2000 });
    } catch {
      toast.error("Clipboard blocked", { description: path });
    }
  };

  return (
    <Card variant="glass" hover="lift">
      <CardHeader className="space-y-2 pb-3">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0 flex-1 space-y-1">
            <a
              href={job.source_url}
              target="_blank"
              rel="noopener noreferrer"
              className="group/link inline-flex items-center gap-1 min-w-0"
              title={job.title ?? ""}
            >
              <span className="text-sm font-semibold truncate group-hover/link:text-[hsl(var(--accent-1))] transition-colors">
                {job.title ?? "Untitled"}
              </span>
              <ExternalLink className="h-3 w-3 text-muted-foreground shrink-0" />
            </a>
            <div className="flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground">
              <span className="inline-flex items-center gap-1">
                <Building2 className="h-3 w-3" />
                {job.company ?? "—"}
              </span>
              <span className="inline-flex items-center gap-1">
                {job.remote ? (
                  <>
                    <Globe className="h-3 w-3" />
                    Remote
                  </>
                ) : (
                  <>
                    <MapPin className="h-3 w-3" />
                    {job.location ?? "—"}
                  </>
                )}
              </span>
            </div>
          </div>
          <ScoreBadge score={job.match_score ?? 0} />
        </div>
        <div className="flex items-center gap-2 text-[10px]">
          <Badge variant="outline" size="sm" className="capitalize">
            {STATUS_LABEL[job.status] ?? job.status}
          </Badge>
          <span className="text-muted-foreground">
            {formatRelative(job.applied_at ?? job.created_at)}
          </span>
        </div>
      </CardHeader>
      <CardContent className="space-y-2">
        <DocRow
          icon={<FileText className="h-3.5 w-3.5" />}
          label="CV"
          path={job.cv_path}
          url={cvUrl}
          onCopy={() => job.cv_path && copyPath(job.cv_path, "CV")}
        />
        <DocRow
          icon={<Mail className="h-3.5 w-3.5" />}
          label="Cover letter"
          path={job.cover_letter_path}
          url={coverUrl}
          onCopy={() =>
            job.cover_letter_path &&
            copyPath(job.cover_letter_path, "Cover letter")
          }
        />
        {job.status === "prepared" && (
          <div className="pt-1.5">
            <Button
              size="sm"
              variant="default"
              shimmer
              onClick={onMarkApplied}
              className="w-full"
            >
              <CheckCircle2 className="h-3.5 w-3.5" />
              Mark as applied
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function DocRow({
  icon,
  label,
  path,
  url,
  onCopy,
}: {
  icon: React.ReactNode;
  label: string;
  path?: string | null;
  url: string;
  onCopy: () => void;
}) {
  if (!path) {
    return (
      <div className="flex items-center gap-2 rounded-lg border border-dashed border-[hsl(var(--border))] px-3 py-2 text-[11px] text-muted-foreground/70">
        {icon}
        {label}: not generated
      </div>
    );
  }
  return (
    <div className="flex items-center gap-2 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--surface))]/40 px-3 py-2">
      <div className="text-[hsl(var(--accent-1))]">{icon}</div>
      <div className="min-w-0 flex-1">
        <div className="text-[11px] font-medium leading-tight">{label}</div>
        <div
          className="text-[10px] text-muted-foreground mono truncate"
          title={path}
        >
          {path}
        </div>
      </div>
      <Button
        size="sm"
        variant="outline"
        onClick={() => window.open(url, "_blank", "noopener,noreferrer")}
        title="Open in new tab"
      >
        <ExternalLink className="h-3.5 w-3.5" />
      </Button>
      <Button size="sm" variant="ghost" onClick={onCopy} title="Copy path">
        <Copy className="h-3.5 w-3.5" />
      </Button>
    </div>
  );
}
